spring:
  application:
    name: bank1
server:
  port: 8081
  servlet:
    context-path: /bank1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
    register-with-eureka: true
    fetch-registry: true